<a href="https://colab.research.google.com/github/Vivicio/Jorge_Armijos/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
aux=np.array([1,2,4,5])
print(aux)
print(aux.shape)

[1 2 4 5]
(4,)


In [ ]:
aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))

(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>


In [ ]:
tmp=np.zeros((4,4))
print(tmp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
tmp=np.full((4,4),5)
print(tmp)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
tmp=np.eye(4,4)
print(tmp)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
tmp=np.ones((4,4))
print(tmp)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
tmp=10*np.random.random((4,4))
print(tmp)

[[3.7329457  6.20043972 0.81928847 4.36746239]
 [7.36637242 4.07459738 3.0113481  3.39205645]
 [1.38655612 5.25106445 0.66804661 2.13175383]
 [6.06113628 3.13116444 3.17582752 3.05849418]]


In [ ]:
print(tmp[:2,:2])
print('-------------------------------')
print(tmp[2:4,2:4])

[[3.7329457  6.20043972]
 [7.36637242 4.07459738]]
-------------------------------
[[0.66804661 2.13175383]
 [3.17582752 3.05849418]]


In [ ]:
print(tmp[1,1])

4.0745973821051


In [ ]:
print(tmp[2,2])

0.6680466113632944


In [ ]:
tmp=10*np.random.random((4,4))
print(tmp)

[[9.58991855 8.47923805 5.87995727 3.99371881]
 [0.41730944 4.94711008 6.5677487  2.2969768 ]
 [8.2012332  7.6675566  7.09906452 6.66098672]
 [3.52683548 8.12075425 0.67365348 4.83165141]]


In [ ]:
mascara=tmp>5
print(mascara)

[[ True  True  True False]
 [False False  True False]
 [ True  True  True  True]
 [False  True False False]]


In [ ]:
print(tmp[mascara])

[9.58991855 8.47923805 5.87995727 6.5677487  8.2012332  7.6675566
 7.09906452 6.66098672 8.12075425]


In [ ]:
mask=(tmp>=2)&(tmp<=4)
print(tmp[mask])

[3.99371881 2.2969768  3.52683548]


In [ ]:
tmp=np.random.randint(0, 11, size=(4, 4))
print(tmp)

[[ 1  5  9  7]
 [ 0  9  1  5]
 [ 0  3  8  0]
 [ 3  7 10  7]]


In [ ]:
mask=np.mod(tmp, 2)==0
print(tmp[mask])

[ 0  0  8  0 10]
